from dvwap.losses import quadratic_vwap_loss, absolute_vwap_loss, volume_curve_loss
from dvwap.deep_static_vwap import StaticVWAP
from dvwap.dynamic_standard_vwap import DynamicVWAPStandardModel
from dvwap import data_formater